services:
  postgres:
    image: postgres:16-alpine
    container_name: sonicflow_db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: sonicflow_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sonicflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data:
