"""criando tabela de likes

Revision ID: 3170acd36455
Revises: cdba22337436
Create Date: 2026-07-07 10:45:54.368831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3170acd36455'
down_revision: Union[str, Sequence[str], None] = 'cdba22337436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    op.add_column('episodes', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('episodes', sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'likes_count')
    op.drop_column('episodes', 'views_count')
    op.drop_table('episode_likes')
    # ### end Alembic commands ###
