"""criando tabela de podcasts

Revision ID: e27963227acb
Revises: 20e6c39085be
Create Date: 2026-07-02 13:04:18.951228

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e27963227acb'
down_revision: Union[str, Sequence[str], None] = '20e6c39085be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('TECHNOLOGY', 'BUSINESS', 'COMEDY', 'EDUCATION', 'HEALTH', 'NEWS', 'SCIENCE', 'SOCIETY', 'SPORTS', 'TRUE_CRIME', name='podcastcategory'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcasts')
    # ### end Alembic commands ###
